stone-payments/pos-mamba-sdk

- packages/components/AppBar/src/AppBarTitle.html
- packages/components/Dialog/src/PromisedDialog.html
- packages/components/Icon/src/Icon.html
[WEBSDK-177](https://stonepayments.atlassian.net/browse/WEBSDK-177)
- Svelte 2.11 changed the behaviour of the `onstate` lifecycle hooke. We must use `onupdate` if we want to manually modify the DOM after a state change.
> -WEBSDK-177-fix-onstate

- packages/configs/eslint/index.js
Linux e Unix(LF - \n) e Windows(CRLF - \r\n) causam problemas de linebreak no build, colocando a regra de desabilitar final de linha, mantendo um padrão consistente.
> Add rule linebreak

- package.json
- packages/webpack/config.base.js
- packages/webpack/helpers/appEntryPoint.js
- packages/webpack/package.json
O arquivo `index.js` dos apps é muito pequeno e sempre será o mesmo, portanto, o `webpack` se encarregará de carregá-lo da memória, e não do HD, deixando o `entrypoint` do app no componente raiz em `index.html`
> Ponto de entrada virtual para o build de App

- packages/pos/drivers/http/simulation.js
- packages/pos/drivers/http/wrappers.js
O promisse de http estava sempre dando reject e nunca resolve, isso porque quando o send dá sucesso driver.getError() retorna um QMap() vazio que mesmo assim é um objeto válido, assim if(driver.getError()) era sempre true.
Troquei para utilizar o signal requestFailed que já é emitido pelo back na 2.4.1 também, mantendo compativel com os POS do parque.
> Handle httpWrapper requestFailed signal

- packages/components/Collection/README.md
[WEBSDK-470](https://stonepayments.atlassian.net/browse/WEBSDK-470)
> WEBSDK-470/Collection

- packages/configs/eslint/index.js
- packages/pos/drivers/app/simulation.js
- packages/pos/package.json
- packages/pos/simulator/plugins/app/manager.js
- packages/pos/simulator/plugins/driver/manager.js
- packages/pos/simulator/plugins/registry/includes/data.js
- packages/pos/simulator/plugins/view/Launcher.html
- packages/pos/simulator/plugins/view/style.pcss
- packages/webpack/config.app.js
- packages/webpack/config.base.js
- packages/webpack/virtual-files/index.browser.js
A gente tava usando um conceito de `drivers` externos que um app poderia ter e os resetando conforme o app fosse fechado no simulador. Entretanto, o "reset" do estado de um driver deveria ser responsabilidade do próprio driver e não do simulador.
> Generalize the simulator usage 

- packages/components/Collection/Row.html
- packages/configs/postcss/includes/uniqueImports.js
- packages/styles/theme.pcss
A altura de 50px pra todas as `Row`s tá um pouco exagerada para a maior parte dos casos e uma `Row` acaba ocupando muito espaço. Antes estavam com `40px` e, para alinhar com o design previsto, trocamos para `49px`. Entretanto, conversando com o Gallez, vimos que algumas `Row`s tem 44px (+1 de borda) de altura e, como a diferença visual entre 49px e 44px é muito pequena, proponho normalizarmos todas as `Row`s com 44px. O ganho de 5px para cada `Row` na tela é bem significativo caso existam várias
> Modify row height to be 44px

- packages/pos/simulator/view/pos/hardware/Screen.html
Firefox is behaving strangely when two stack-contexts are together
(translateZ(0) and filter). To fix this, the color map filter is now
applied only when running the simulator not on firefox.
> internal: 🏭 fix firefox scroll breaking

- packages/components/App/package.json
- packages/components/AppBar/package.json
- packages/components/Barcode/package.json
- packages/components/Button/package.json
- packages/components/Collection/package.json
- packages/components/Dialog/package.json
- packages/components/Icon/package.json
- packages/components/Input/package.json
- packages/components/Printable/package.json
- packages/components/Progress/package.json
- packages/components/QRCode/package.json
- packages/components/Range/package.json
- packages/components/Sprite/package.json
- packages/components/Switch/package.json
- packages/components/Tabs/README.md
- packages/components/Tabs/TabPane.html
- packages/components/Tabs/Tabs.html
- packages/components/Tabs/package.json
Using the `route` operating mode of the` changeOn` parameter causes the flaps to be changed by the route of the application. This is useful for remembering the position of the tab index for internal routes, and back in the browser history, or for when you want to enter a page displaying a specific index.
> feat: 🎸 Create operating mode by route

- packages/components/Input/Input.html
Resolve problema onde é necessário ter o valor com máscara além de valor sem máscara, para tratamentos em casos específicos, como usar `String.split("/")` em uma data `01/01/2019`, pra separar seus componentes. Hoje o método retorna apenas `value`, sem máscara (ex: `01012019`)
VSTS: [97732](https://stonepagamentos.visualstudio.com/POS%20-%20Mamba/_workitems/edit/97732)
> feat: 🎸 add value to validation callback

- packages/components/App/App.html
Conserta bug na SDK onde os eventos de Keystroke e Shortcut de uma página estão sendo propagados para o contexto de outra página.
VSTS: [97733](https://stonepagamentos.visualstudio.com/POS%20-%20Mamba/_workitems/edit/97733)
> fix: 🐛 prevent shortcut and keystroke propagate event to other pages

- packages/components/Printable/Printable.html
- packages/components/Printable/package-lock.json
I included a new state to show the information when the printer was a break because just exists one rule that checks whether there is a store state called transactionType or pre auth is not enabled.
With that, we can use this information on all apps that make sense to show it.
> fix: 🐛 Fixed print bug

- packages/components/Printable/Printable.html
Adição de um slot na mensagem de erro do objeto Printable, o que permite alterar a mensagem padrão.
Torna a mensagem customizável - a mensagem padrão atual não é aplicável ao caso do Ton, por exemplo, que usa um app "Recibos" ao invés de "Reimpressão".
> feat: 🎸 enable customizable printable error message

- yarn.lock
This reverts commit 4a2525c5872b8fca90c188e3ded6ccb4d0dd3f58.
> Revert from before wrong sdk pre-publish

- packages/pos/simulator/view/pos/panels/POS.html
- packages/utils/models.js
- Tornar recursos de POS obsoletos
- Atualizar painel de recursos no Simulador
- [[487260] [MambaSDK] Passar a ver os recursos do POS através do back](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_workitems/edit/487260)
- [[487528] [Ativação] Aplicar novos métodos de recursos](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_workitems/edit/487528)
> Fix/utils v5.3.0

- packages/utils/models.js
- Alguns métodos de recurso, `hasSmallScreen` e `hasKeyboard` por ex., estavam dando falso positivo
- [[511376] Método de recurso retornando falso positivo](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_workitems/edit/511376)
> fix: 🐛 capabilities return

- packages/components/Dialog/Confirmation.html
Esse PR faz a alteração do componente `CorfirmationDialog`, adicionando a variável `buttonSize`.
O objetivo é permitir que o app consumindo esse componente possa alterar o tamanho do botão utilizado. Essa alteração faz parte da correção do app DeviceTest, onde para POS de tela pequena, a tela do teste de leitura do cartão ficava recortada.
Card do bug: [501066](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_boards/board/t/Mamba%20-%20Plataforma/Stories/?workitem=501066)
Essa modificação não deve gerar nenhum impacto no funcionamento dos apps que consomem esse componente, pois o valor padrão usado foi o mesmo que estava fixado anteriormente.
> feat: Include button size input for CorfirmationDialog component

- packages/webpack/config.app.build.js
- packages/webpack/helpers/consts.js
- packages/webpack/helpers/loaders.js
* Resolve static assets to the same structure on bundle target folder.
* Ensure that app icon is copied to the same folder structure declared.
* Read `SDK_ASSETS_FOLDER` from envs, or keep default to `@mamba`
> New static assets structure

- packages/org/Image.html
Fix some problems related to organization application fallback images.
- Fix an infinite loop of both org and fallback images fails.
- Add `on:load` event to the `Image.html` in order to app consumes.
- Fix the way a fallback image loads.
> Org fallback image fixes

- packages/components/Icon/example/Example.html
missing comma that was breaking the bundle
The bundle was breaking due to a missing comma in the Example.html page
> fix: missing comma that was breaking the bundle

- packages/cli/namespaces/app/commands/deploy.js
The flags for rsync should be configured on `~/.ssh/config`.
> Remove keys algorithms from rsync command

- packages/components/Printable/Printable.html
Adiciona a propriedade `fullscreen` para o `Dialog` de erro de impressão no componente `Printable`.
> failure print dialog without appbar

- packages/components/Keyboard/src/controllers/PhysicalKeyboard.ts
Clear the `focusin` event after keyboard has been destroyed
> Virtual keyboard clear listener

- tools/repo_setup.py
:sparkles: PMIPA-5055 Stash changes before update branch on repo_setup. Fixes bug on git clone of repo_setup of SAL
> ✨PMIPA-5055 Stash changes before update branch on repo_setup

- packages/components/Dialog/Dialog.html
Foi implementado ao componente `Dialog` a opção de adicionar qualquer elemento antes do título, tornando este componente mais adaptável aos estilos.
A demanda deste [card](https://mundipagg.atlassian.net/browse/PMIPA-5576) motivou a implementação deste PR.
> Add slot before title on Dialog

- tools/repo_setup.py
Este PR ajusta o download da toolchain ndk26 da gertec ao rodar o repo_setup para não realizá-lo de forma desnecessária, acrescentando uma verificação se a toolchain já existe na pasta do mal.
Atualmente, sempre que o `repo_setup.py` é executado (tanto manualmente quanto ao trocar de branch), caso haja algum artifact descrito no `repo_settings.json`, é verificado se o mesmo já foi baixado em momentos anteriores, porém a verificação era feita da seguinte forma: o script olhava na pasta de download dos artifacts se ele existia e, caso não existisse, baixava e instalava o artifact no repositório, de acordo com as informações presentes no arquivo `repo_settings.json`.
Desta forma, sempre que a pasta de `output` era apagada (sempre que roda o script de build com a opção `-r`, a pasta é …
> PMIPA-11171 - Improove repo_setup to avoid unecessary toolchain download
