stone-payments/pos-mamba-sdk

- package.json
- packages/configs/package.json
> Update mamba configs package

- packages/webpack/package.json
> Fix @mambasdk/configs version

- package.json
- packages/cli/package.json
- packages/components/App/package.json
- packages/components/AppBar/package.json
- packages/components/Barcode/package.json
- packages/components/Button/package.json
- packages/components/Collection/package.json
- packages/components/Dialog/package.json
- packages/components/Icon/package.json
- packages/components/Input/package.json
- packages/components/Pos/package.json
- packages/components/Printable/package.json
- packages/components/Progress/package.json
- packages/components/QRCode/package.json
- packages/components/Range/package.json
- packages/components/Sprite/package.json
- packages/components/Switch/package.json
- packages/configs/package.json
- packages/native/package.json
- packages/store/package.json
- packages/styles/package.json
> Add contributors and licenses

- package.json
- packages/components/Icon/example/Example.html
- tools/rollup/config.component.watch.js
> Remove postinstall and fix .svelte

- packages/configs/package.json
> Fix babel dep version

- packages/components/Progress/README.md
Documentei o Circle Progress e Progress Bar juntos pois não faria sentido de outra forma.
[WEBSDK-67](https://stonepayments.atlassian.net/browse/WEBSDK-67)
> -WEBSDK-67-Doc-Componentes-Progress

- packages/components/Button/README.md
Button Documentation
[WEBSDK-67](https://stonepayments.atlassian.net/browse/WEBSDK-67)
> -WEBSDK-67-Doc-Componentes-Button

- packages/components/Printable/package.json
- packages/components/Printable/src/Printable.html
- packages/native/src/printer/README.md
[WEBSDK-66](https://stonepayments.atlassian.net/browse/WEBSDK-66)
> -WEBSDK-66-Doc-Native-Printer

- packages/native/src/keyboard/README.md
> Fix-Keyboard-Docs

- packages/native/src/system/mock.js
> Remove old documentation

- packages/native/src/payment/README.md
- packages/native/src/payment/mock.js
[WEBSDK-64](https://stonepayments.atlassian.net/browse/WEBSDK-64)
Adicionando documentação e fix no mock
> -WEBSDK-64-Doc-Api-Nativa-Payment

- packages/components/Input/README.md
- packages/components/Input/src/Input.html
[WEBSDK-72](https://stonepayments.atlassian.net/browse/WEBSDK-72)
> WEBSDK-72-Doc-Input

- packages/components/Sprite/README.md
[WEBSDK-76](https://stonepayments.atlassian.net/browse/WEBSDK-76)
> -WEBSDK-76-Doc-Sprite-Gif

- packages/components/Collection/README.md
[WEBSDK-74](https://stonepayments.atlassian.net/browse/WEBSDK-74)
> -WEBSDK-74-Doc-Collection

- packages/components/Range/README.md
- packages/components/Range/example/Example.html
[WEBSDK-73](https://stonepayments.atlassian.net/browse/WEBSDK-73)
> Websdk 73 doc range

- packages/components/Progress/package.json
Sem tarefa.
PR necessário para testar a pasta de exemplo no NPM.
> Update version and add example files

- packages/components/Progress/README.md
- packages/components/Progress/package.json
Sem tarefa.
Conserta propriedades do README.md
> Fix README.md tag props and add version

- packages/components/Progress/README.md
- packages/components/Progress/package.json
Sem tarefa.
Conserta README a incrementa versão ...
> Publish/progress 0.0.5

- packages/components/Dialog/example/Example.html
Sem tarefa.
Ajustes da Documentação.
> Remove component não utilizado(Sprite) do exemplo Dialog/example

- packages/pos/docs/cookie.md
Foram alteradas também as assinaturas das funções.
> Corrige o texto e melhora o entendimento de Cookie

- packages/pos/docs/payment.md
> Corrige texto de payment

- packages/pos/docs/system.md
> Corrige textos e deixa algumas informações mais claras.

- packages/pos/docs/http.md
Alterada também a assinatura da função.
> Corrige o texto e melhora o entendimento de Http

- packages/components/Barcode/README.md
> Corrige textos simples do Barcode

- packages/components/App/README.md
> Corrige o texto do componente App

- packages/pos/docs/http.md
> Fixes documentation

- package-lock.json
- package.json
- packages/cli/package.json
- packages/components/App/package.json
- packages/components/AppBar/package.json
- packages/components/Barcode/package.json
- packages/components/Button/package.json
- packages/components/Collection/package.json
- packages/components/Dialog/package.json
- packages/components/Icon/package.json
- packages/components/Input/package.json
- packages/components/Printable/package.json
- packages/components/Progress/package.json
- packages/components/QRCode/package.json
- packages/components/Range/package.json
- packages/components/Sprite/package.json
- packages/components/Switch/package.json
- packages/configs/package.json
- packages/pos/drivers/cancellation/simulation.js
- packages/pos/package.json
- packages/pos/simulator/libs/main.js
- packages/store/package.json
- packages/styles/package.json
- packages/webpack/package.json
- packages/webpack/plugins/MambaFixesPlugin.js
> V1.0.0 prealpha.8

- packages/pos/docs/http.md
> Fix path import

- packages/components/Dialog/README.md
> Adicionando eventos na documentação

- packages/components/App/README.md
[WEBSDK-231](https://stonepayments.atlassian.net/browse/WEBSDK-231)
Tava faltando uma documentação básica do que o componente mais importante do aplicativo fazia.
> Add some basic doc to App component

- packages/pos/docs/system.md
> Correção na documentação

- packages/pos/docs/payment.md
> Adicionando order_id

- packages/components/Icon/Icon.html
- packages/components/Input/Input.html
- packages/components/Input/Money.html
- packages/components/Input/README.md
- packages/components/Input/example/Example.html
- packages/components/Input/libs/dynamic-mask.js
- packages/components/Input/libs/masker.js
- packages/components/Input/libs/maskit.js
- packages/components/Input/libs/tokens.js
- tools/rollup/config.component.watch.js
[WEBSDK-216 ](https://stonepayments.atlassian.net/browse/WEBSDK-216 )
> Funcionalidade de máscara no Input

- packages/pos/docs/http.md
> Adicionando opção DEV

- packages/components/Input/README.md
> Adicionando

- packages/cli/src/namespaces/app/commands/format.js
- packages/cli/src/namespaces/app/commands/lint.js
- packages/cli/src/namespaces/new/commands/app.js
- packages/cli/src/namespaces/pos/index.js
- packages/cli/src/utils.js
[WEBSDK-249](https://stonepayments.atlassian.net/browse/WEBSDK-249)
> Fix dep installation on windows. Fixes #197

- packages/pos/docs/Card.md
> Adicionado documetação do drive Card

- packages/pos/docs/payment.md
> Remoção dos eventos de cartão

- packages/pos/docs/storage.md
> Correção nos exemplos

- packages/pos/api/system.js
- packages/pos/docs/system.md
- packages/pos/drivers/system/simulation.js
- packages/pos/drivers/system/wrappers.js
> Adicionando função de modificar adaptador de rede

- packages/pos/docs/http.md
> Fix JSON at example

- packages/components/Range/Range.test.js
- tools/jest/__mocks__/TestApp.html
Adicionando Testes do Componente Range.
> WEBSDK-371/Tests Range

- packages/components/App/App.html
- packages/configs/jest/globals.js
[WEBSDK-418](https://stonepayments.atlassian.net/browse/WEBSDK-418)
> Reset the scroll position after every router page update

- packages/pos/docs/payment.md
> Fix doc function name payment

- packages/components/Switch/README.md
[WEBSDK-479](https://stonepayments.atlassian.net/browse/WEBSDK-479)
> WEBSDK-479/Switch

- packages/components/App/README.md
[WEBSDK-466](https://stonepayments.atlassian.net/browse/WEBSDK-466)
> WEBSDK-466/App

- packages/components/Range/README.md
[WEBSDK-477](https://stonepayments.atlassian.net/browse/WEBSDK-477)
> WEBSDK-477/Range

- packages/components/Printable/README.md
[WEBSDK-474](https://stonepayments.atlassian.net/browse/WEBSDK-474)
> WEBSDK-474

- packages/components/App/App.html
[WEBSDK-491](https://stonepayments.atlassian.net/browse/WEBSDK-491)
> Fix event path

- packages/pos/docs/http.md
[WEBSDK-499](https://stonepayments.atlassian.net/browse/WEBSDK-499)
> Add paramater encodeURI

- packages/pos/docs/http.md
- packages/pos/drivers/http/wrappers.js
> Encapsulate convertion data in http to string

- packages/components/Switch/Switch.html
- packages/configs/package.json
- packages/configs/postcss/index.js
- packages/styles/colors.pcss
- packages/styles/theme.pcss
[WEBSDK-539](https://stonepayments.atlassian.net/browse/WEBSDK-539)
> Align @mamba/switch style

- packages/components/App/App.html
- packages/components/Collection/README.md
- packages/components/Collection/Row.html
- packages/components/Collection/Row.test.js
- packages/components/Collection/example/Example.html
- packages/components/Icon/Icon.html
- packages/components/Icon/assets/calendar.svg
- packages/components/Switch/Switch.html
- packages/pos/simulator/view/pos/Wrapper.html
- packages/styles/colors.pcss
- packages/styles/theme.pcss
- tools/rollup/config.component.watch.js
[WEBSDK-549](https://stonepayments.atlassian.net/browse/WEBSDK-549)
`lerna run start --scope=@mamba/collection --stream`
> Align @mamba/collection style

- packages/webpack/config.app.dev.js
- packages/webpack/helpers/loaders.js
[WEBSDK-564](https://stonepayments.atlassian.net/browse/WEBSDK-564)
> Fix sourcemap not working on dev envs

- packages/pos/drivers/system/simulation.js
> Websdk 535 launcher

- packages/components/Dialog/Dialog.html
[WEBSDK-599](https://stonepayments.atlassian.net/browse/WEBSDK-599)
> Make @mamba/dialog use static vars to control the app lock

- packages/cli/lib/loadPlugins.js
[WEBSDK-613](https://stonepayments.atlassian.net/browse/WEBSDK-613)
> WEBSDK-613/Enable Mamba CLI to support more than one namespace

- packages/pos/simulator/view/pos/panels/General.html
[WEBSDK-633](https://stonepayments.atlassian.net/browse/WEBSDK-633)
> Fix max length of stone code field

- packages/components/AppBar/AppBar.html
- packages/components/AppBar/AppBar.test.js
Vamos precisar disso já já
Com esse PR daria pra pegar os clicks da appbar com: 
`this.root.on('appbar:goHome', ...)`
`this.root.on('appbar:goBack', ...)`
`this.root.on('appbar:closeApp', ...)`
> Add appbar:goHome,goBack,closeApp root events for analytics tracking

- changelog.config.js
- commitlint.config.js
- package.json
- packages/pos/simulator/drivers/card.js
- packages/pos/simulator/view/pos/Card.html
- packages/pos/simulator/view/pos/apps/Launcher.html
Add events: `cardInserted`, `cardRemoved`, `cardToggled`
> internal: 🏭 Add explicit simulated card events

- packages/components/Tabs/CHANGELOG.md
- packages/components/Tabs/README.md
- packages/components/Tabs/TabPane.html
- packages/components/Tabs/TabPane.test.js
- packages/components/Tabs/Tabs.html
- packages/components/Tabs/Tabs.test.js
- packages/components/Tabs/example/Example.html
- packages/components/Tabs/package.json
- packages/styles/theme.pcss
[WEBSDK-703](https://stonepayments.atlassian.net/browse/WEBSDK-703)
> Implement @mamba/tabs component

- packages/components/App/AdminLock.html
- packages/components/App/App.html
- packages/components/App/App.test.js
- packages/components/App/README.md
- packages/components/App/package.json
- packages/components/Button/Button.html
- packages/pos/simulator/drivers/merchant.js
- packages/pos/simulator/view/pos/panels/General.html
- packages/styles/colors.pcss
- packages/styles/theme.pcss
Add admin lock option for App component
[WEBSDK-714](https://stonepayments.atlassian.net/browse/WEBSDK-714)
> Websdk 714/travar saida do app

- packages/components/Tabs/example/Example.html
> @mamba/tabs - remove button from example

- package.json
- packages/utils/README.md
- packages/utils/date.js
- packages/utils/index.js
- packages/utils/tests/date.test.js
> feat: 🎸 Add format date yyyy/mm/dd to utils

- packages/pos/drivers/http/wrappers.js
> If the partner has added the Content type header, it was added to the wrapper again, causing an error in the request.

- packages/components/Input/Text.html
- packages/components/Input/libs/virtualKeyboard.js
- packages/styles/settings.pcss
> Refactor keyboard

- packages/utils/date.js
> feat: 🎸 Add compareTime method

- packages/configs/eslint/index.js
- packages/pos/simulator/drivers/http.js
Conserta HTTP Status Code`s de sucesso ( 2xx )
Conserta HTTP Status Code`s de erro (3xx)
Conserta import/no-cycle não configurado
> fix: 🐛 HTTP Status Codes do wrapper do simulador

- packages/pos/docs/merchant.md
- packages/pos/simulator/drivers/merchant.js
- packages/pos/simulator/view/pos/ControlPanel.html
- packages/pos/simulator/view/pos/apps/Launcher.html
- packages/pos/simulator/view/pos/panels/Merchant.html
Add Merchant getInfo to simulation and simulator panel, also add this feature in docs.
Nowadays we already has this feature in POS but not documented or either simulated in our SDK.
The tests were made by changing the merchant information in panel.
> feat: 🎸 Add getInfo to Merchant and panel

- packages/pos/docs/app.md
- packages/pos/docs/system.md
- packages/pos/simulator/drivers/app.js
- packages/pos/simulator/drivers/system.js
> Expondo versão do app e do sistema

- packages/components/App/App.html
- packages/components/App/README.md
- packages/components/AppBar/AppBar.html
The methods setNavigableRoute and resetRoute have been created to customize route when the user click on the back button using a customize route, the setNavigableRoute accept two params, the first is a specific route and the second is the params that you want, resetRoute just reset route.
> feat: 🎸 New feature add methods to specific route

- packages/components/App/App.html
- packages/components/App/App.test.js
- packages/components/App/README.md
- packages/components/AppBar/AppBar.html
- packages/components/AppBar/AppBar.test.js
If add `remove="true"`, all AppBar components will be hidden if you want to show utilize `remove="false"` in the `<AppBarModifier /> ` component.
Example: 
**AppBar:** `<AppBar title="Title" remove="true" />`
**AppBarModifier:** `<AppBarModifier title="Title" remove="false" />`
> feat: 🎸 New feature remove header appBar

- packages/configs/eslint/index.js
- packages/configs/eslint/template.js
- packages/configs/helpers/clientEnvironment.js
- packages/configs/package.json
- packages/webpack/config.base.js
- packages/webpack/package.json
This allow you to control app build target, feature flags, versions for
production...Then you can use inside you code to control application
features and behaviors. For more information access
https://webpack.js.org/plugins/define-plugin/
> feat: 🎸 adds the ability to configure feature flags

- packages/components/Input/Money.html
- packages/components/Input/README.md
Implement a new attr on the Money Input to treat an edge case bug on the payment app
> feat: 🎸 Implement readonlyOnEnter attr on money input

- packages/components/Tabs/TabPane.html
- packages/components/Tabs/Tabs.html
Refactored TabPane props that caused tooltip bugs on POS
> fix: 🐛 Refactored TabPane props that caused tooltip bugs on POS

- packages/components/Carousel/Carousel.test.js
- packages/components/Radio/Radio.test.js
> Radio carousel tests

- packages/components/Tabs/README.md
> docs: ✏️ TAB: title renamed to label

- packages/components/Dialog/PopUp.test.js
- packages/components/Dialog/Popup.html
- packages/components/Dialog/README.md
- packages/components/Dialog/example/Example.html
> feat: 🎸 new popup component

- packages/utils/date.js
> feat: 🎸 date validation now denies 24 as hour

- packages/components/Input/Input.html
https://stonepagamentos.visualstudio.com/POS%20-%20Mamba/_boards/board/t/Squad%20Front/Stories/?workitem=105619
> refactor: 💡 password now gets visible only clicking on icon

- packages/components/Printable/Printable.html
> fix: 🐛 remove log

- packages/components/Input/Input.html
- packages/components/Input/package-lock.json
> fix: 🐛 Fixed input text color when itś disabled

- packages/components/AppBar/AppBar.html
- packages/components/AppBar/package-lock.json
This change will allow us to do something like a check or save data before the app close clicking on home button or back button.
> feat: 🎸 State to allow to do something before app close or back to home

- packages/components/Input/Input.html
- packages/components/Input/Keyboard.html
- packages/components/Input/package-lock.json
These changes fix keyboard close action and hide the error message when the input length is 0.
> fix: 🐛 Fix input bugs

- packages/components/Input/Keyboard.html
- packages/components/Input/package-lock.json
> fix: 🐛 Remove event when ondestroy is called

- packages/pos/docs/system.md
> docs: ✏️ include activateStonecode, new System method

- packages/components/App/App.html
- packages/components/App/App.test.js
- packages/components/App/package-lock.json
- packages/components/AppBar/AppBar.html
- packages/components/AppBar/Modifier.html
- packages/components/AppBar/package-lock.json
- tools/jest/mocks/Root.html
> fix: 🐛 Fix doBeforeClose state

- lerna.json
> Go Lerna independent version

- packages/cli/namespaces/app/commands/build.js
- packages/webpack/config.app.build.js
- packages/webpack/package-lock.json
The platform prefix will be included only when the build option is **all** or **more than one**.
> feat: 🎸 Included BUILD_ALL invironment variable

- packages/cli/CHANGELOG.md
- packages/cli/package-lock.json
- packages/cli/package.json
> chore(release): :robot: publish

- packages/utils/models.js
Add D199 and D230 models to utils models list for ton
> feat: 🎸 add D199 and D230 POS models to utils models list

- packages/components/Input/NumericKeyboard.html
- packages/components/Input/package.json
Fix the numeric keyboard position (from absolute to fixed), remove empty
space on the right and resize icons.
> fix: 🐛 fix numeric keyboard position and improve key distribution

- packages/components/Input/NumericKeyboard.html
- packages/components/Input/package.json
add invalidade method do NumericKeyboard and remove some warnings.
> Keyboard invalidate and warnings

- packages/pos/lib/terminal-settings/index.js
- packages/pos/package.json
Reverts stone-payments/pos-mamba-sdk#747
> Revert "Detect current declared System or $System(useful for simulator)"

- packages/webpack/config.app.build.js
* Remove files copy redundant of images assets
> refactor: 💡 remove files copy redundant

- packages/components/Collection/Row.html
Corrige o import do color **neutral500** do `packages/components/Collection/Row.html`
> Fix color import

- packages/components/AppBar/AppBar.html
- packages/components/AppBar/package.json
Corrige o tamanho da fonte do título para os pos de tela pequena.
> AppBar [v4.0.3]

- packages/components/Flatlist/FlatList.html
- packages/components/Flatlist/NavBar.html
- packages/components/Flatlist/helpers.js
- packages/components/Flatlist/package.json
- Ajusta o scroll com o componente `NavBar`;
- Adiciona o estilo para a classe `disabled` no `NavBar`;
- Modifica a ordem das opções do `NavBar`;
> Flatlist [6.2.0]

- packages/components/Keyboard/EXAMPLES.md
- Nova página dentro de Keyboard com exemplos diretos do uso do componente
> docs: ✏️ include real-life examples for Keyboard

- packages/pos/simulator/view/pos/panels/POS.html
- Incluir novas funções de recursos (que deveria ter sido incluído no `@mamba/utils v5.3.0`)
- Remover recursos obsoletos de arquivos do Simulador
- [[487260] [MambaSDK] Passar a ver os recursos do POS através do back](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_workitems/edit/487260)
- [[487528] [Ativação] Aplicar novos métodos de recursos](https://stonepagamentos.visualstudio.com/Tribo%20Meios%20de%20Pagamento/_workitems/edit/487528)
> Fix/utils v5.3.0

- packages/components/Dialog/Confirmation.html
- packages/components/Dialog/package.json
Este PR adiciona um objeto de retorno no **_ConfirmationDialog_** informando se a opção selecionada foi feita através da tela (touch) ou pelo teclado físico através da propriedade _handler_.
> feature: dialog handler response

- .gitignore
- .yarnrc.yml
- package.json
- packages/components/App/App.html
- packages/components/App/includes/EventDispatcher.js
- packages/components/App/includes/KeystrokeRegister.js
- packages/components/Dialog/Confirmation.html
- packages/components/Dialog/Dialog.html
- packages/components/Dialog/README.md
- packages/components/Flatlist/FlatList.html
- packages/components/Flatlist/README.md
- packages/components/Flatlist/components/parent.html
- packages/components/Keyboard/Keyboard.html
- packages/components/Keyboard/package.json
- packages/components/Keyboard/tsconfig.json
- packages/core/tsconfig.json
- packages/webpack/helpers/consts.js
- packages/webpack/helpers/getHTMLTemplate.js
- yarn.lock
* Fix critial Keystorke events
* Fix telemetry emit type generated by Flatlist, Dialog and Keystrokes
* Simplify Confirmation dialog enter/close
* Add RemoteJs tag injection
* Force yarn 1x(classic) for  yarn 2+ users
* Try to send `keyCode` through synthetic mouse event
> Fixes physical keyboard evens

- packages/components/Input/Input.html
Reverts stone-payments/pos-mamba-sdk#892
> Revert "fix: 🐛 remove the reset of the error message"

- packages/components/Flatlist/DefaultRow.html
- packages/components/Flatlist/FlatList.html
- packages/components/Flatlist/README.md
- packages/components/Flatlist/components/parent.html
- Adicionei uma nova prop para esconder o prefix decorator
Usar o npm link (ou yarn link) para fazer o testa no pagamento
> Prop for hide prefix decorator

- packages/components/Flatlist/FlatList.html
- packages/components/Flatlist/helpers.js
Fix scroll in component flatlist
> bug fix scroll flatlist

- packages/webpack/config.app.build.js
- packages/webpack/helpers/consts.js
[\[PMIPA-944\] - [Campanhas] Criar novo app Campanhas](https://mundipagg.atlassian.net/browse/PMIPA-944)
Este PR adiciona uma task no build do webpack para copiar o conteúdo de assets estáticos (que precisam ir no bundle sem importação explícita), necessário para o implementação no novo app de Novidades (Campanhas).
> static assets folder

- package.json
- packages/components/Keyboard/package.json
- packages/components/Keyboard/src/Keyboard.ts
- packages/components/Keyboard/src/common/CursorWorker.ts
- packages/components/Keyboard/src/controllers/GeneralKeyboard.ts
- packages/components/Keyboard/src/controllers/PhysicalKeyboard.ts
- packages/components/Keyboard/tests/generalKeyboard.spec.ts
- yarn.lock
- Fix the use of the generic keyboard methods and its return values.
- Add basic generic keyboard tests
> Generic keyboard values

- .vscode/settings.json
- packages/configs/babel/sdk.js
- packages/configs/nyc/index.js
- packages/configs/package.json
- packages/configs/playwright/consts.js
- packages/configs/playwright/index.js
- packages/webpack/helpers/consts.js
- yarn.lock
Centralizes playwright configuration
> Playwright / Code Coverage config

- packages/utils/models.js
Adicionei a POS D230 na listas dos modelos com touch
> fix: 🐛 add D230 as a POS with touch

- packages/components/Button/Button.html
- packages/components/Button/README.md
- packages/pos/drivers/system/enums.js
- packages/pos/simulator/boot.js
- packages/pos/simulator/drivers/system.js
- packages/pos/simulator/plugins/registry/includes/initScriptHook.js
- packages/pos/simulator/plugins/registry/manager.js
* Fix broken methods of:
```
System.getTonOrganizationName
System.getStoneOrganizationName
System.getWLPagarmeOrganizationName
```
* Add active acquirer method
* Add registry hook for playwright
> Fix missing Organization object for simulator system org methods

- packages/components/Flatlist/helpers.js
Correction in  scrollTo method on Flatlist when an item was manipulated by the navbar
> Fix scrollTo in Flatlist

- .github/CODEOWNERS
- tools/repo_setup.py
- PMIPA-5165 
- Add repo_setup.py script on tools folder
- Update codeowners file
> PMIPA-5165 Add repo_setup.py and change CODEOWNERS file

- tools/_git_hooks/install-hooks.sh
- tools/_git_hooks/post-checkout
🏗️ PMIPA-5165 Add Git Hooks to tools
> 🏗️ PMIPA-5165 Add Git Hooks to tools

- tools/repo_initialization.sh
- tools/repo_setup.py
PMIPA-5165 - Add repo_initialization.sh
> PMIPA-5165 ✨ Add repo_initialization.sh

- tools/repo_initialization.sh
- tools/repo_setup.py
- Add -c parameter to repo_setup to define the type of clone in repo_setup. Options: "ssh" and "https". Default: "ssh"
- Adds 2 retries when trying to clone or update a submodule
> PMIPA-5244 Update repo_setup

- tools/repo_initialization.sh
- tools/repo_setup.py
- PMIPA-5420 repo_setup now updates itself
- Fix git fetch bug on tags fetch and remove depth 1
> ✨PMIPA-5420 repo_setup automagically updates itself + fix repo_setup bug on tag fetch

- tools/repo_initialization.sh
Fix repo_init run on pipeline
Remove gitignore log
wget less verbose
> Repo_init improvements

- tools/repo_setup.py
repo_setup fixes and improvements: Fixed repo clone step, create init_repository, repo_initialized and get_target_of_submodule functions. Created bypass_auto_update argument to bypass file verification and update.
> repo_setup fixes and improvements

- packages/components/Dialog/Confirmation.html
Modifica o componente para enviar propriedades que serão enviadas no objeto de telemetria
> [PMIPA-6312] Change Confirmation dialog to send telemetry

- tools/repo_initialization.sh
Fix when download dest dir doesn't exist on repo_init download
> PMIPA-8564 - Fix when download dest dir doesn't exist on repo_init download

- tools/repo_setup.py
Add required param to handle optional repositories
> Add required param to repo_setup.py

- tools/repo_setup.py
> Fix repo_setup azure artifact download when dir doesn't exist

- tools/repo_setup.py
> Fix azure login while downloading SDKs

- tools/repo_setup.py
> Pmipa 9738 build do appbundle qt 6 para os terminais da gertec

- tools/repo_setup.py
> Fix azure login without token

- tools/repo_setup.py
[PMIPA-9938](https://mundipagg.atlassian.net/browse/PMIPA-9938)
- Adicionado novo parâmetro --archive_list/-a para especificar quais artefatos devem ser baixados.
- Criado método filter_archives para gerenciar a lógica de filtragem dos artefatos:
- Em ambiente local: baixa todos os artefatos quando nenhum argumento é fornecido.
- Na pipeline: só baixa artefatos quando explicitamente solicitados via parâmetro, evitando downloads desnecessários.
- Refatorado código de filtragem para melhor compreensão.
---
[PMIPA-9938]: https://allstone.atlassian.net/browse/PMIPA-9938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Repo setup esta sempre baixando o sdk da gertec

- tools/repo_setup.py
This reverts commit 7b0706cdbaf53d24bf9dbdd6a0904730c4466604.
PR para poder viabilizar o build de apps para montagem do hotfix.
---
> Revert "Repo setup esta sempre baixando o sdk da gertec (#995)"

- tools/repo_setup.py
This reverts commit c8c490fc2e847165b96e73c653ecd23fbe14a5da.
---
> Revert "Revert "Repo setup esta sempre baixando o sdk da gertec

- tools/repo_setup.py
Anteriormente, quando um git hook era alterado no mamba, ele não era atualizado. Agora ao fazer checkout em uma branch, o git hook sera atualizado
---
> PMIPA-10394 - Add step to update git hooks

- tools/repo_setup.py
Reverts stone-payments/pos-mamba-sdk#998
> Revert "PMIPA-10394 - Add step to update git hooks"

- tools/mamba-environment/README.md
- tools/mamba-environment/mamba-environment.sh
[PMIPA-12348](https://mundipagg.atlassian.net/browse/PMIPA-12348)
Inclusão de script de instalação de sistema, que estava previamente no repo pos-mamba (fechado). Este repo é aberto e portanto se presta melhor para um script de instalação geral.
Também atualizado para uma série de novidades, mudanças, pequenos bugs, formatações, mensagens, etc
---
[PMIPA-12348]: https://allstone.atlassian.net/browse/PMIPA-12348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Pmipa 12348 move environment script
